routes/admin.php
<?php

/*
 *
 *  admin panel
 *
 */

/*
Route::get('test', function(){
    app('Illuminate\Bus\Dispatcher')->dispatch(new \App\Jobs\StatusSwitching());
});
*/

Route::get('admin/login', 'Admin\AdminController@getLogin');

Route::get('logout', 'Auth\AuthController@logout');

Route::post('admin/login', 'Admin\AdminController@postLogin');

Route::group(['middleware' => ['admin'], 'prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/', ['uses' => 'Admin\AdminController@index', 'as' => 'admin.index']);

    Route::get('json/changevisibility', 'Admin\JsonController@getChangeVisibility');

    Route::get('json/delete', 'Admin\JsonController@getDeleteModel');

    Route::resource('lists', 'Admin\ListsController');

    Route::get('get-users', 'Admin\UserController@ajaxData');

    Route::resource('users', 'Admin\UserController');

    Route::resource('content', 'Admin\ContentController');

    Route::get('clear-cache', 'Admin\AdminController@clearCache');

    Route::get('get-products', 'Admin\ProductsController@ajaxData');

    Route::resource('products', 'Admin\ProductsController');

    Route::get('translations', 'Admin\TranslationsController@edit');

    Route::post('translations', 'Admin\TranslationsController@save');

    Route::get('get-categories', 'Admin\CategoriesController@ajaxData');

    Route::resource('categories', 'Admin\CategoriesController');

    Route::get('get-agents', 'Admin\AgentsController@ajaxData');

    Route::resource('agents', 'Admin\AgentsController');

    Route::get('get-news', 'Admin\NewsController@ajaxData');

    Route::resource('news', 'Admin\NewsController');

    Route::resource('regions', 'Admin\RegionController');

    Route::get('get-regions', 'Admin\RegionController@ajaxData');

    Route::resource('region_groups', 'Admin\RegionGroupsController');

    Route::get('get-region-groups', 'Admin\RegionGroupsController@ajaxData');

    Route::resource('parameters', 'Admin\ParametersController');

    Route::resource('reviews', 'Admin\ReviewsController');

    Route::get('get-parameters', 'Admin\ParametersController@ajaxData');

    Route::get('json/remove-parameter', 'Admin\ParametersController@removeParameter');

    Route::get('json/remove-parameter-value', 'Admin\ParametersController@removeParameterValue');

    Route::get('json/get-category-parameters',  'Admin\ParametersController@getCategoryParameters');

    Route::get('products-agents-excel', 'Admin\ProductsController@productsAgentsPage');
    Route::post('generate-products-agents-excel', 'Admin\ProductsController@productsAgentsExcel')->name('generate-products-agents-excel');
});


/*
 *
 *  photomanager
 *
 */
// upload
Route::group(['middleware' => ['admin']], function () {
    Route::any('photos/upload', 'Admin\PhotosController@upload');
    Route::get('photos/getphotos', 'Admin\PhotosController@getJSONPhotos');
    Route::get('photos/changesort', 'Admin\PhotosController@changesort');
    Route::get('photos/delete/{id}', 'Admin\PhotosController@destroy');
    Route::post('photos/crop', 'Admin\PhotosController@postCrop');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'CommonController@index')->name('index');

Route::get('category/{slug}', 'ProductsController@getCategory')->name('get-category');

Route::get('rent', 'ProductsController@getRent')->name('rent');

Route::get('rent/{slug}', 'ProductsController@getRentCategory')->name('rent-category');

Route::get('sale', 'ProductsController@getSale')->name('sale');

Route::get('sale/{slug}', 'ProductsController@getSaleCategory')->name('sale-category');

Route::get('products/{slug}', 'ProductsController@getProduct')->name('product');

Route::get('get-category-filters/{id}', 'ProductsController@getCategoryFilters')->name('get-category-filters');

Route::get('get-objects/{type}', 'ProductsController@getObjects')->name('get-objects');

Route::get('get-top-objects', 'ProductsController@getTopObjects')->name('get-top-objects');

Route::get('get-related-objects/{id}', 'ProductsController@getRelatedObjects')->name('get-related-objects');

Route::get('get-agent-objects/{id}', 'ProductsController@getAgentObjects')->name('get-agent-objects');

Route::get('news', 'NewsController@getAllNews')->name('news');

Route::get('news/{slug}', 'NewsController@getOneNews')->name('get-one-news');

Route::get('search', 'ProductsController@search')->name('search');

Route::get('get-search-results', 'ProductsController@getSearchResults')->name('get-search-results');

Route::post('send-contact-form', 'CommonController@sendContactForm')->name('send-contact-form');


/*Route::get('elements', function () {
    return view('elements');
})->name('elements');*/

Route::get('team1200522', 'CommonController@getTeam')->name('team');

/*Route::get('team-test', 'CommonController@getTeamTest')->name('team-test');*/

Route::get('objects-list', function () {
    return view('objects-list');
})->name('objects-list');

Route::post('amo/new-lead', 'RealtorController@newLead')->name('amo.new-lead');
Route::get('amo/updateToken', 'RealtorController@updateToken')->name('amo.updateToken');

Route::get('agent/{id}', 'CommonController@getAgent')->name('get-agent');

/*Route::get('object', function () {
    return view('object');
})->name('object');*/

Route::get('experts', function () {
    return view('experts');
})->name('experts');

/*Route::get('projects', function () {
    return view('projects');
})->name('projects');*/

Route::get('about', function () {
    return view('about');
})->name('about');

Route::get('our-team', 'CommonController@getOurTeam')->name('our-team');

Route::get('rieltor-objects', function () {
    return view('rieltor-objects');
})->name('rieltor-objects');

Route::get('contacts', function () {
    return view('contacts');
})->name('contacts');

Route::get('careers', function () {
    return view('careers');
})->name('careers');

Route::get('investors', function () {
    return view('investors');
})->name('investors');

Route::get('developers', function () {
    return view('developers');
})->name('developers');

/*Route::get('philosophy-page', function () {
    return view('philosophy');
})->name('philosophy-page');*/

Route::get('mission-page', function () {
    return view('mission');
})->name('mission-page');


Route::get('advices', function () {
    return view('advices');
})->name('advices');

Route::get('services', function () {
    return view('services');
})->name('services');

/*Route::get('content-page', function () {
    return view('content-page');
})->name('content-page');*/

Route::get('generate-pdf/{id}', 'ProductsController@generatePdf')->name('generate-pdf');

Route::post('send-contact-form', 'CommonController@sendContactForm')->name('send-contact-form');
Route::post('send-booking-form', 'CommonController@sendBookingForm')->name('send-booking-form');
Route::post('send-pdf-form', 'CommonController@sendPDFForm')->name('send-pdf-form');
Route::post('send-pdf-form', 'CommonController@sendPDFForm')->name('send-pdf-form');

Route::post('send-order-call-form', 'CommonController@sendOrderCall')->name('send-order-call-form');
Route::post('send-newsletter-form', 'CommonController@sendNewsletterForm')->name('send-newsletter-form');
Route::post('send-consultation-form', 'CommonController@sendConsultationForm')->name('send-consultation-form');
Route::post('send-agent-call-form', 'CommonController@sendAgentCallForm')->name('send-agent-call-form');
Route::post('send-mobile-call-form', 'CommonController@sendMobileCallForm')->name('send-mobile-call-form');
Route::post('send-agent-mortgage-form', 'CommonController@sendAgentMortgageForm')->name('send-agent-mortgage-form');

// Localization
Route::get('/js/lang.js', function () {
    $lang = app()->getLocale();

    $files   = glob(resource_path('lang/' . $lang . '/vue.php'));
    $strings = [];

    foreach ($files as $file) {
        $name           = basename($file, '.php');
        $strings[$name] = require $file;
    }

    header('Content-Type: text/javascript');
    echo('window.i18n = ' . json_encode($strings) . ';');
    exit();
})->name('assets.lang');

// ---- AmoRealtor 25/09/2022
Route::post('/realtor/webhook', 'RealtorController@webhook')->name('realtor/webhook');
Route::post('/realtor/update-label', 'RealtorController@updateLabel')->name('realtor/updateLabel');
// ---- AmoRealtor end

Route::get('privacy-policy', 'CommonController@getPrivacyPolicy')->name('privacy-policy');

Route::post('/simpals/upload-999', 'SimpalsController@addAdvert')->name('add-advert');

//!!!!этот роут должен быть всегда последним!!!!!
//!!!!этот роут должен быть всегда последним!!!!!
//!!!!этот роут должен быть всегда последним!!!!!
//!!!!этот роут должен быть всегда последним!!!!!
//!!!!этот роут должен быть всегда последним!!!!!
Route::get('{slug}', ['uses'=>'CommonController@getBySlug', 'as' => 'content']);


/*
 * Route patterns
 */
Route::pattern('id', '\d+');
Route::pattern('hash', '[a-z0-9]+');
Route::pattern('hex', '[a-f0-9]+');
Route::pattern('uuid', '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}');
Route::pattern('base', '[a-zA-Z0-9]+');
Route::pattern('slug', '[a-z0-9-]+');
Route::pattern('username', '[a-z0-9_-]{3,16}');

app/Models/Region.php
<?php

namespace App\Models;

use App\Traits\CommonTrait;
use Illuminate\Database\Eloquent\Model;

class Region extends Model
{
    use CommonTrait;

    protected $guarded = [];

    public function group()
    {
        return $this->hasOne('App\Models\RegionGroup', 'id', 'group_id');
    }

    /**
     * @return array
     */
    public static function getSelectArray()
    {
        $region_groups = RegionGroup::with('regions')->get();

        $regions = [];

        foreach ($region_groups as $group) {
            $regions[$group->name] = $group->regions->pluck('name', 'id')->toArray();
        }

        return $regions;
    }
}

app/Http/Controllers/Admin/RegionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Region;
use App\Models\RegionGroup;
use Illuminate\Http\Request;
use Datatables;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Session;

class RegionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.regions.index');
    }

    /**
     * Process datatables ajax request.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function ajaxData()
    {
        $query = Region::orderBy('sort');

        return self::datatablesCommon($query)
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.regions.edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = array(
            'name.*' => 'required',
            'group_id' => 'required',
        );

        $this->validate($request, $rules);

        return $this->save($request, null);
    }

    private function save(Request $request, $id)
    {
        $region = Region::updateOrCreate(['id' => $id], $request->all());

        if ($request->ajax()) {
            return response()->json([
                'region_id' => $region->id,
                'regions' => Region::getSelectArray(),
            ]);
        }

        // redirect
        Session::flash('message', 'Сохранено!');
        return redirect()->route('admin.regions.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Region::find($id);
        return view('admin.regions.edit')->with(compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = array(
            'name.*' => 'required',
            'group_id' => 'required',
        );

        $this->validate($request, $rules);

        return $this->save($request, $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        Region::destroy($id);
        Session::flash('message', 'Удалено');
        return back();
    }
}

resources/views/admin/regions/groups/edit.blade.php
@extends('admin.body')
@section('title', 'Группы')


@section('centerbox')
    <div class="page-header">
        <h1> <a href="{{ route('admin.region_groups.index')  }}">Группы</a> <small><i class="ace-icon fa fa-angle-double-right"></i> Редактирование </small> </h1>
    </div>

    @if(!isset($data))
        {{ Form::open(['url' => 'admin/region_groups', 'class' => 'form-horizontal']) }}
    @else
        {{ Form::open(['url' => 'admin/region_groups/' . $data->id, 'method' => 'put', 'class' => 'form-horizontal']) }}
    @endif

    <div class="row">
        <div class="form-group">
            {{ Form::label('name[ru]', 'Название (ru)', ['class'=>'col-sm-3 control-label no-padding-right']) }}
            <div class="col-sm-9">
                {{ Form::text('name[ru]', (isset($data->name) ? $data->name : old('name.ru')), array('class' => 'col-sm-11 col-xs-12 name_ru')) }}
            </div>
        </div>
        <div class="form-group lang-ro" >
            {{ Form::label('name[ro]', 'Название (ro)', ['class'=>'col-sm-3 control-label no-padding-right']) }}
            <div class="col-sm-9">
                {{ Form::text('name[ro]', (isset($data->name_ro) ? $data->name_ro : old('name.ro')), array('class' => 'col-sm-11 col-xs-12')) }}
            </div>
        </div>
        <div class="form-group lang-en">
            {{ Form::label('name[en]', 'Название (en)', ['class'=>'col-sm-3 control-label no-padding-right']) }}
            <div class="col-sm-9">
                {{ Form::text('name[en]', (isset($data->name_en) ? $data->name_en : old('name.en')), array('class' => 'col-sm-11 col-xs-12')) }}
            </div>
        </div>
    </div><!-- /.row -->

    <div class="form-actions">
        {{ Form::submit('Сохранить', array('class' => 'btn btn-success')) }}
    </div>

    {{ Form::close() }}

@endsection

resources/views/admin/regions/groups/index.blade.php
@extends('admin.body')
@section('title', 'Список групп')

@section('centerbox')
    <div class="page-header">
        <h1> <a href="{{ route('admin.regions.index') }}">Районы</a> <small><i class="ace-icon fa fa-angle-double-right"></i> Группы </small> </h1>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <a class="btn  btn-success" href="{{ route('admin.region_groups.create') }}">
                <i class="ace-icon fa fa-plus-square-o  bigger-120"></i>
                Создать
            </a>
            <div class="clearfix"><div class="pull-right tableTools-container"></div></div>
            <div class="table-header"> Список групп </div>

            <table id="dynamic-table" class="table table-striped table-bordered table-hover dataTable">
                <thead>
                <tr>
                    <th align="center">ID</th>
                    <th align="center">Наименование</th>
                    <th align="center">Создан</th>
                    <th align="center"><i class="fa fa-cogs"></i></th>
                </tr>
                </thead>
                <tbody bgcolor="white"></tbody>
            </table>
        </div><!-- /.col-xs-12 -->
    </div><!-- /.row -->
@stop

@section('scripts')

    <script>
        var columns = [
            { data : 'id' },
            { data : 'name' },
            { data : 'created_at' },
            { data : 'actions', className : 'center' }
        ];
    </script>

    @include('admin.partials.datatable-init-ajax', ['ajax' => 'admin/get-region-groups'])

@endsection